version: '3.7'
services:
  mysql:
    container_name: mysql
    build:
      context: ./.docker/mysql
    env_file: .env
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3316:3306"
  apache_php:
    container_name: laravel-vue
    build:
      args:
        user: $DOCKER_USER_NAME
        uid: $DOCKER_USER_UID
      context: ./.docker/apache
    volumes:
      - ./:/home/project
    working_dir: /home/project
    ports:
      - "8080:80"
    links:
      - "mysql:db_mysql"
    depends_on:
      mysql:
        condition: service_started
